"""
Central task emission helper — used by all routers to create cross-module tasks.
Writes directly to db["tasks"] so tasks appear in the Administration inbox immediately.
"""
from app.mock_db import db
import uuid
from datetime import datetime, timedelta

ROLE_TO_USER = {
    "re_director": {"user_id": "user-001", "name": "Sarah Chen"},
    "lease_admin":  {"user_id": "user-002", "name": "James Okafor"},
    "finance":      {"user_id": "user-003", "name": "Priya Mehta"},
    "legal":        {"user_id": "user-004", "name": "Tom Walsh"},
}


def emit_task(
    title: str,
    source: str,
    action_type: str,
    assignee_role: str,
    priority: str,
    org_id: str = "org1",
    lease_id: str | None = None,
    dispute_id: str | None = None,
    watched_by_role: str | None = None,
    requires_approval: bool = False,
    approval_requested_from_role: str | None = None,
    due_days: int | None = None,
    notes: str | None = None,
) -> dict:
    task_id = str(uuid.uuid4())
    assignee = ROLE_TO_USER.get(assignee_role, {})
    watcher = ROLE_TO_USER.get(watched_by_role, {}) if watched_by_role else {}
    approval_user = ROLE_TO_USER.get(approval_requested_from_role or "re_director", {})

    due_date = None
    if due_days is not None:
        due_date = (datetime.utcnow() + timedelta(days=due_days)).strftime("%Y-%m-%d")

    task = {
        "taskId": task_id,
        "orgId": org_id,
        "title": title,
        "source": source,
        "sourceRecordId": lease_id or dispute_id or task_id,
        "sourceRecordLabel": title[:60],
        "actionType": action_type,
        "priority": priority,
        "status": "open",
        "assignedTo": assignee.get("user_id"),
        "assignedToName": assignee.get("name"),
        "watchedBy": [watcher["user_id"]] if watcher else [],
        "dueDate": due_date,
        "createdAt": datetime.utcnow().isoformat(),
        "completedAt": None,
        "isAutoGenerated": True,
        "requiresApproval": requires_approval,
        "approvalStatus": "pending" if requires_approval else None,
        "approvalRequestedFrom": approval_user.get("user_id") if requires_approval else None,
        "linkedLeaseId": lease_id,
        "linkedDisputeId": dispute_id,
        "notes": notes,
    }
    db["tasks"][task_id] = task
    return task
