from app.mock_db import db
import uuid
import random
from datetime import date, timedelta, datetime

random.seed(99)

USERS = [
    {"user_id": "user-001", "name": "Sarah Chen", "role": "re_director"},
    {"user_id": "user-002", "name": "James Okafor", "role": "lease_admin"},
    {"user_id": "user-003", "name": "Priya Mehta", "role": "finance"},
    {"user_id": "user-004", "name": "Tom Walsh", "role": "legal"},
]


def _pick_leases(n=10):
    leases = list(db["leases"].values())
    return random.sample(leases, min(n, len(leases)))


def seed_tasks():
    if db.get("tasks"):
        return
    db["tasks"] = {}
    today = date.today()
    leases = _pick_leases(10)

    seed_data = [
        {
            "title": "Review renewal option exercise window",
            "source": "renewals", "actionType": "exercise_renewal_option",
            "priority": "high", "status": "open",
            "assignedTo": "user-001", "watchedBy": ["user-002"],
            "daysOffset": 5, "isAutoGenerated": True, "requiresApproval": True,
            "approvalStatus": "pending", "approvalRequestedFrom": "user-001",
        },
        {
            "title": "Upload insurance certificate — Mumbai BKC Flagship",
            "source": "obligations", "actionType": "upload_document",
            "priority": "high", "status": "overdue",
            "assignedTo": "user-002", "watchedBy": ["user-001"],
            "daysOffset": -3, "isAutoGenerated": True, "requiresApproval": False,
        },
        {
            "title": "Reconcile CAM statement — Q1",
            "source": "payments", "actionType": "reconcile_cam",
            "priority": "medium", "status": "in_progress",
            "assignedTo": "user-003", "watchedBy": ["user-001", "user-002"],
            "daysOffset": 14, "isAutoGenerated": False, "requiresApproval": False,
        },
        {
            "title": "Log formal notice — break clause exercise",
            "source": "administration", "actionType": "send_formal_notice",
            "priority": "high", "status": "pending_approval",
            "assignedTo": "user-004", "watchedBy": ["user-001"],
            "daysOffset": 2, "isAutoGenerated": False, "requiresApproval": True,
            "approvalStatus": "pending", "approvalRequestedFrom": "user-001",
        },
        {
            "title": "Confirm rent payment received — Bengaluru MG Road",
            "source": "payments", "actionType": "confirm_payment",
            "priority": "medium", "status": "open",
            "assignedTo": "user-003", "watchedBy": [],
            "daysOffset": 7, "isAutoGenerated": True, "requiresApproval": False,
        },
        {
            "title": "Percentage rent report due — Mumbai Palladium Mall",
            "source": "obligations", "actionType": "submit_report",
            "priority": "high", "status": "overdue",
            "assignedTo": "user-002", "watchedBy": ["user-003"],
            "daysOffset": -7, "isAutoGenerated": True, "requiresApproval": False,
        },
        {
            "title": "Initiate renewal analysis — Delhi Select Citywalk",
            "source": "renewals", "actionType": "start_analysis",
            "priority": "medium", "status": "open",
            "assignedTo": "user-001", "watchedBy": ["user-004"],
            "daysOffset": 30, "isAutoGenerated": False, "requiresApproval": False,
        },
        {
            "title": "Dispute overbilled CAM charge — Hyderabad Banjara Hills",
            "source": "payments", "actionType": "send_dispute_letter",
            "priority": "high", "status": "open",
            "assignedTo": "user-004", "watchedBy": ["user-001", "user-003"],
            "daysOffset": 10, "isAutoGenerated": False, "requiresApproval": True,
            "approvalStatus": None,
        },
        {
            "title": "Letter of credit renewal — Chennai Anna Nagar",
            "source": "obligations", "actionType": "renew_lc",
            "priority": "medium", "status": "open",
            "assignedTo": "user-002", "watchedBy": [],
            "daysOffset": 20, "isAutoGenerated": True, "requiresApproval": False,
        },
        {
            "title": "Review lease expiry decision — Kolkata Park Street",
            "source": "renewals", "actionType": "make_decision",
            "priority": "low", "status": "done",
            "assignedTo": "user-001", "watchedBy": [],
            "daysOffset": -10, "isAutoGenerated": False, "requiresApproval": False,
        },
    ]

    for i, d in enumerate(seed_data):
        lease = leases[i % len(leases)]
        task_id = str(uuid.uuid4())
        due = today + timedelta(days=d["daysOffset"])
        db["tasks"][task_id] = {
            "taskId": task_id,
            "title": d["title"],
            "source": d["source"],
            "sourceRecordId": lease["lease_id"],
            "sourceRecordLabel": lease.get("store_name", "Unknown"),
            "actionType": d["actionType"],
            "priority": d["priority"],
            "status": d["status"],
            "assignedTo": d["assignedTo"],
            "assignedToName": next((u["name"] for u in USERS if u["user_id"] == d["assignedTo"]), None),
            "watchedBy": d["watchedBy"],
            "dueDate": due.isoformat(),
            "createdAt": (today - timedelta(days=random.randint(1, 14))).isoformat(),
            "completedAt": (today - timedelta(days=1)).isoformat() if d["status"] == "done" else None,
            "isAutoGenerated": d["isAutoGenerated"],
            "requiresApproval": d["requiresApproval"],
            "approvalStatus": d.get("approvalStatus"),
            "approvalRequestedFrom": d.get("approvalRequestedFrom"),
            "approvalNotes": None,
            "linkedLeaseId": lease["lease_id"],
            "notes": "",
        }


def seed_obligations():
    if db.get("obligations"):
        return
    db["obligations"] = {}
    today = date.today()
    leases = _pick_leases(8)

    obligation_templates = [
        {"type": "insurance_certificate", "label": "Insurance Certificate", "daysOffset": -15, "status": "overdue"},
        {"type": "insurance_certificate", "label": "Insurance Certificate", "daysOffset": 20, "status": "due"},
        {"type": "percentage_rent_report", "label": "% Rent Sales Report", "daysOffset": -5, "status": "overdue"},
        {"type": "percentage_rent_report", "label": "% Rent Sales Report", "daysOffset": 30, "status": "due"},
        {"type": "letter_of_credit", "label": "Letter of Credit Renewal", "daysOffset": 45, "status": "due"},
        {"type": "letter_of_credit", "label": "Letter of Credit Renewal", "daysOffset": 90, "status": "compliant"},
        {"type": "ti_allowance", "label": "TI Allowance Claim", "daysOffset": 60, "status": "compliant"},
        {"type": "keep_open_covenant", "label": "Keep Open Covenant", "daysOffset": 0, "status": "not_applicable"},
    ]

    for i, tmpl in enumerate(obligation_templates):
        lease = leases[i % len(leases)]
        obl_id = str(uuid.uuid4())
        due = today + timedelta(days=tmpl["daysOffset"])
        db["obligations"][obl_id] = {
            "obligationId": obl_id,
            "leaseId": lease["lease_id"],
            "locationName": lease.get("store_name", "Unknown"),
            "storeCode": lease.get("store_code", ""),
            "type": tmpl["type"],
            "label": tmpl["label"],
            "dueDate": due.isoformat(),
            "status": tmpl["status"],
            "lastActionDate": (today - timedelta(days=random.randint(10, 60))).isoformat() if tmpl["status"] == "compliant" else None,
            "notes": "",
        }


def seed_renewals():
    if db.get("renewals"):
        return
    db["renewals"] = {}
    today = date.today()
    leases = _pick_leases(8)

    stages = ["watching", "watching", "analysis", "analysis", "negotiation", "negotiation", "final", "final"]
    decisions = ["undecided", "stay", "undecided", "relocate", "stay", "stay", "stay", "relocate"]

    for i, lease in enumerate(leases):
        renewal_id = str(uuid.uuid4())
        months = random.randint(4, 18)
        expiry = today + timedelta(days=months * 30)
        db["renewals"][renewal_id] = {
            "renewalId": renewal_id,
            "leaseId": lease["lease_id"],
            "locationName": lease.get("store_name", "Unknown"),
            "storeCode": lease.get("store_code", ""),
            "expiryDate": expiry.isoformat(),
            "monthsRemaining": months,
            "stage": stages[i],
            "decision": decisions[i],
            "decisionDate": (today - timedelta(days=5)).isoformat() if decisions[i] != "undecided" else None,
            "notes": "",
            "currentRentMonthly": lease.get("monthly_rent", 80000),
            "currency": lease.get("currency", "INR"),
        }


def seed_payments():
    if db.get("payments"):
        return
    db["payments"] = {}
    today = date.today()
    leases = _pick_leases(8)

    current_period = today.strftime("%Y-%m")
    statuses = ["on_time", "overbilled", "underbilled", "late", "pending", "on_time", "disputed", "pending"]

    for i, lease in enumerate(leases):
        payment_id = str(uuid.uuid4())
        expected = lease.get("monthly_rent", 5000)
        status = statuses[i % len(statuses)]
        if status == "on_time":
            actual = expected
            variance = 0.0
        elif status == "overbilled":
            actual = round(expected * random.uniform(1.05, 1.20), 2)
            variance = round(actual - expected, 2)
        elif status == "underbilled":
            actual = round(expected * random.uniform(0.80, 0.95), 2)
            variance = round(actual - expected, 2)
        elif status == "late":
            actual = expected
            variance = 0.0
        elif status == "disputed":
            actual = round(expected * random.uniform(1.10, 1.30), 2)
            variance = round(actual - expected, 2)
        else:
            actual = None
            variance = None

        db["payments"][payment_id] = {
            "paymentId": payment_id,
            "leaseId": lease["lease_id"],
            "locationName": lease.get("store_name", "Unknown"),
            "storeCode": lease.get("store_code", ""),
            "period": current_period,
            "expectedAmount": expected,
            "actualAmount": actual,
            "paymentDate": (today - timedelta(days=random.randint(0, 5))).isoformat() if actual is not None else None,
            "variance": variance,
            "status": status,
            "currency": lease.get("currency", "INR"),
        }


def seed_workflow_rules():
    if db.get("workflow_rules"):
        return
    db["workflow_rules"] = {
        "rule-001": {
            "ruleId": "rule-001",
            "actionType": "send_dispute_letter",
            "label": "Send Dispute Letter",
            "requiresApproval": True,
            "approvalRole": "re_director",
            "isConfigurable": True,
        },
        "rule-002": {
            "ruleId": "rule-002",
            "actionType": "exercise_renewal_option",
            "label": "Exercise Renewal Option",
            "requiresApproval": True,
            "approvalRole": "re_director",
            "isConfigurable": False,
        },
        "rule-003": {
            "ruleId": "rule-003",
            "actionType": "send_formal_notice",
            "label": "Send Formal Legal Notice",
            "requiresApproval": True,
            "approvalRole": "re_director",
            "isConfigurable": True,
        },
    }


def seed_month_end_checklist():
    if db.get("month_end_checklist"):
        return
    today = date.today()
    db["month_end_checklist"] = {
        "chk-001": {"itemId": "chk-001", "label": "Confirm all rent payments received", "category": "payments", "isDone": True, "dueDate": today.isoformat()},
        "chk-002": {"itemId": "chk-002", "label": "Review outstanding CAM reconciliations", "category": "cam", "isDone": True, "dueDate": today.isoformat()},
        "chk-003": {"itemId": "chk-003", "label": "Check insurance certificate expirations", "category": "obligations", "isDone": False, "dueDate": today.isoformat()},
        "chk-004": {"itemId": "chk-004", "label": "Log formal notices sent this month", "category": "administration", "isDone": True, "dueDate": today.isoformat()},
        "chk-005": {"itemId": "chk-005", "label": "Update renewal pipeline stages", "category": "renewals", "isDone": False, "dueDate": today.isoformat()},
        "chk-006": {"itemId": "chk-006", "label": "Review overdue tasks and escalations", "category": "administration", "isDone": False, "dueDate": today.isoformat()},
    }


def seed_all():
    seed_tasks()
    seed_obligations()
    seed_renewals()
    seed_payments()
    seed_workflow_rules()
    seed_month_end_checklist()
    print(f"Administration seed: {len(db['tasks'])} tasks, {len(db['obligations'])} obligations, "
          f"{len(db['renewals'])} renewals, {len(db['payments'])} payments, "
          f"{len(db['workflow_rules'])} workflow rules, {len(db['month_end_checklist'])} checklist items")
